version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    networks:
      - dev-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_NODE_ID: '1'
      CLUSTER_ID: 'vA86_xBqS2uw6XSJhehxBA'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,EXTERNAL://:9093,CONTROLLER://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - dev-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8081:8080'
    environment:
      SERVER_PORT: '8080'
      KAFKA_CLUSTERS_0_NAME: 'cluster01'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    depends_on:
      - kafka
    networks:
      - dev-net

volumes:
  kafka-data:

networks:
  dev-net:
    driver: bridge
